/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moduleTest;

import ch.bildspur.artnet.ArtNetBuffer;
import ch.bildspur.artnet.ArtNetClient;

import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws SocketException {
        System.out.println("Sending DMX data...");

        byte[] dmxData = new byte[512];


        Enumeration<NetworkInterface> netInterfaces = NetworkInterface.getNetworkInterfaces();
        ArrayList<NetworkInterface> netInterfaceList = new ArrayList<NetworkInterface>();
        int nInterfaces = 0;
        while (netInterfaces.hasMoreElements()) {
            netInterfaceList.add(netInterfaces.nextElement());
            System.out.println("(" + nInterfaces + ") = " + netInterfaceList.get(nInterfaces).getDisplayName());
            nInterfaces++;
        }

        Scanner interfaceScanner = new Scanner(System.in);
        System.out.println("Select Network Interface: ");
//        String userInput = interfaceScanner.nextLine();
//        int choice = Integer.valueOf(userInput);
        int choice = 6;
        System.out.println("Selected " + netInterfaceList.get(choice).getDisplayName());

        NetworkInterface ni = netInterfaceList.get(choice);
        InetAddress address = ni.getInetAddresses().nextElement();

        ArtNetClient artnet = new ArtNetClient(new ArtNetBuffer(), 6454, 6454);
        artnet.start(address);

        // send data to localhost
        boolean onFlag = false;
        for(int i = 0; i < 4096; i++){
            if(onFlag == false){
                dmxData[0] = (byte) 255;
                dmxData[1] = 0;
                dmxData[2] = 0;
                dmxData[3] = (byte) 255;

            }else{
                dmxData[0] = 0;
                dmxData[1] = 0;
                dmxData[2] = 0;
                dmxData[3] = 0;
            }

            artnet.broadcastDmx(0, 1, dmxData);

            try{
                Thread.sleep(100);
            }catch(Exception ignored){

            }

            if(onFlag){
                onFlag = false;
            }else{
                onFlag = true;
            }
        }

        dmxData[0] = 0;
        dmxData[1] = 0;
        dmxData[2] = 0;
        dmxData[3] = 0;

        artnet.broadcastDmx(0, 1, dmxData);

        artnet.stop();

        System.out.println("DMX data sent!");
    }
}
